"""
state.py — LangGraph shared state definition.

BlogState is a TypedDict that flows through every node in the graph.
All fields are optional (None / 0 / []) at startup and get populated
as the pipeline runs.
"""

from typing import Any, TypedDict


class BlogState(TypedDict):
    """Shared state passed between every LangGraph node."""

    # --- RSS phase ---
    articles: list[dict[str, Any]]  # Raw Article dicts from RSS feeds

    # --- Topic phase ---
    selected_topic: str  # The topic chosen by the LLM

    # --- Research phase ---
    research_summary: str  # Firecrawl search + scrape summarized by LLM

    # --- Writing phase ---
    outline: str  # Blog outline generated by writer
    draft: str  # Current blog draft

    # --- Critic phase ---
    critic_score: int  # Score from current critic pass (0-100)
    critic_feedback: str  # Feedback string from critic

    # --- Loop tracking ---
    attempts: int  # How many write→critique cycles have run
    best_score: int  # Highest score seen so far
    best_draft: str  # Draft that produced best_score
